channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.10.12                # https://pyreadiness.org/3.10/ 
  - tesseract=5.3.3               # https://prefix.dev/channels/conda-forge/packages/tesseract
  - pip=23.2.1                    # https://prefix.dev/channels/conda-forge/packages/pip
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - rpaframework==28.0.0        # https://rpaframework.org/releasenotes.html
    - rpaframework-recognition==5.2.3
