channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.9.13                 # https://pyreadiness.org/3.9/ 
  - tesseract=5.2.0               # https://anaconda.org/conda-forge/tesseract
  - pip=22.2.2                    # https://pip.pypa.io/en/stable/news/
  - pip:
    # Define pip packages here. 
    # https://pypi.org/
    - rpaframework==17.7.0        # https://rpaframework.org/releasenotes.html
    - rpaframework-recognition==5.0.0
