name: Windows Test Run

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to run the workflow on'
        required: true
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
    
    - name: Cache RCC executable
      uses: actions/cache@v2
      with:
        path: rcc.exe
        key: ${{ runner.os }}-rcc-${{ hashFiles('rcc.exe') }}
        restore-keys: ${{ runner.os }}-rcc-${{ hashFiles('rcc.exe') }}

    - name: Get RCC
      shell: powershell
      run: |
        if [ ! -f rcc.exe ]; then
          Write-Host "RCC not found in cache. Downloading..."
          Invoke-WebRequest -Uri 'https://downloads.robocorp.com/rcc/releases/latest/windows64/rcc.exe' -OutFile 'rcc.exe'
        else
          Write-Host "Using RCC from cache."
        fi

    - name: Run
      shell: powershell  
      run: .\rcc.exe run --task "Demo Windows Locators with Calculator"

    - uses: actions/upload-artifact@v1
      with:
        name: log.html
        path: output/log.html
