name: Windows Test Run

on:
  workflow_dispatch:
    
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  windows-test-run:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3

    - name: Get RCC version
      id: rcc-version
      shell: powershell
      run: |
        $rcc_version = curl.exe -Ls https://downloads.robocorp.com/rcc/releases/latest/version.txt
        echo "::set-output name=rcc_version::$rcc_version"

    - name: Cache RCC executable
      uses: actions/cache@v2
      with:
        path: rcc.exe
        key: ${{ runner.os }}-rcc-${{ steps.rcc-version.outputs.rcc_version }}

    - name: Get RCC
      shell: powershell
      run: |
        if (-not (Test-Path -Path 'rcc.exe')) {
          curl.exe -o rcc.exe https://downloads.robocorp.com/rcc/releases/latest/windows64/rcc.exe
          .\rcc.exe version
        } else {
          echo "Using RCC from cache."
        }
  
    - name: Generate env. hash
      id: generate_env_hash
      shell: powershell
      run: |
        $hash = .\rcc.exe ht hash conda.yaml --silent
        echo "Environment hash: $hash"
        echo "::set-output name=env_hash::$hash"
  
    - name: Cache environment
      uses: actions/cache@v2
      with:
        path: |
          $Env:LOCALAPPDATA\robocorp\hololib
          $Env:LOCALAPPDATA\robocorp\holotree
        key: ${{ runner.os }}-env-${{ steps.generate_env_hash.outputs.env_hash }}
  
    - name: Build env.
      shell: powershell
      run: | 
        .\rcc.exe ht vars conda.yaml
        .\rcc.exe ht catalogs
  
    - name: Run
      shell: powershell  
      run: .\rcc.exe run --task "Demo Windows Locators with Calculator"

    - uses: actions/upload-artifact@v1
      with:
        name: log.html
        path: output/log.html
