name: Windows Test Run

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to run the workflow on'
        required: true
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  windows-test-run:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
    
    - name: Cache RCC executable
      uses: actions/cache@v2
      with:
        path: rcc.exe
        key: ${{ runner.os }}-rcc-${{ hashFiles('rcc.exe') }}
        restore-keys: ${{ runner.os }}-rcc-

    - name: Get RCC
      shell: powershell
      run: |
        if (-not (Test-Path -Path 'rcc.exe')) {
          Write-Host "RCC not found in cache. Downloading..."
          Invoke-WebRequest -Uri 'https://downloads.robocorp.com/rcc/releases/latest/windows64/rcc.exe' -OutFile 'rcc.exe'
        } else {
          Write-Host "Using RCC from cache."
        }
    
  
    - name: Generate env. hash
      id: generate_env_hash
      shell: powershell
      run: |
        $hash = .\rcc.exe ht hash conda.yaml --silent
        echo "env_hash=$hash" >> $GITHUB_STATE
  
    - name: Cache environment
      uses: actions/cache@v2
      with:
        path: |
          $Env:LOCALAPPDATA\robocorp\hololib
          $Env:LOCALAPPDATA\robocorp\holotree
        key: ${{ runner.os }}-env-${{ steps.generate_env_hash.outputs.env_hash }}
        restore-keys: ${{ runner.os }}-env-
  
    - name: Build env.
      shell: powershell
      run: |
        .\rcc.exe ht env conda.yaml
        $folderPath = "$Env:LOCALAPPDATA\robocorp\hololib"
        $folderSize = (Get-ChildItem -Recurse $folderPath | Measure-Object -Property Length -Sum).Sum
        Write-Host "Size of $folderPath: $($folderSize / 1MB) MB"
        $folderPath = "$Env:LOCALAPPDATA\robocorp\holotree"
        $folderSize = (Get-ChildItem -Recurse $folderPath | Measure-Object -Property Length -Sum).Sum
        Write-Host "Size of $folderPath: $($folderSize / 1MB) MB"

    - name: Run
      shell: powershell  
      run: .\rcc.exe run --task "Demo Windows Locators with Calculator"

    - uses: actions/upload-artifact@v1
      with:
        name: log.html
        path: output/log.html
